
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zero-scaling.controllers.dockerize.io
  resources:
  - scalebackinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zero-scaling.controllers.dockerize.io
  resources:
  - scalebackinfoes/status
  verbs:
  - get
  - patch
  - update
